### ISSUE TITLE
Issue: a small migration problem that I don't really understand

### ISSUE THREAD

**Issue by raymondrwang** [raymondrwang/Not-Chinese-Food#1]
@amadden80 

When I delete a party from the restaurant, I'd like to set a boolean `has_paid` to `true` instead of deleting it from the database completely. This works for my boolean in my party model, but not my order model, even though I'm using the same language; I'm getting the error message `uninitialized constant PartyController::PartyOrders` and I can't figure out what I'm doing wrong here.

**Comment by amadden80** [comment]
Shouldn't it be `PartyOrder`?
